[package]
name = "http-server-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sea-orm = { version = "1.0.0-rc.5", features = [ 
        "sqlx-sqlite", 
        "macros" ,
        "runtime-tokio"
] }
log = "0.4"