[package]
name = "entities"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entities"
path = "src/mod.rs"

[dependencies]
sea-orm = "1.0.0-rc.5"
serde = { version = "1.0.208", features = [ "derive" ] }
